import { google } from "googleapis";

export type CalendarDraftEvent = {
  title: string;
  date: string;
  kind: "deadline" | "milestone" | "travel";
};

export type GoogleCalendarSyncResult = {
  ok: boolean;
  mode: "live" | "simulated";
  calendarId: string;
  insertedCount: number;
  errors: string[];
};

export async function syncCalendarDraftEvents(
  auth: any,
  events: CalendarDraftEvent[],
  calendarId: string = "primary"
): Promise<GoogleCalendarSyncResult> {
  if (!auth) {
    return { ok: true, mode: "simulated", calendarId, insertedCount: events.length, errors: [] };
  }
  const calendar = google.calendar({ version: "v3", auth });
  let insertedCount = 0;
  const errors: string[] = [];

  for (const event of events.slice(0, 50)) {
    try {
      const summaryPrefix =
        event.kind === "deadline" ? "Apres Deadline" : event.kind === "travel" ? "Apres Travel" : "Apres Trip";
      const response = await calendar.events.insert({
        calendarId,
        requestBody: {
          summary: `${summaryPrefix}: ${event.title}`,
          start: { date: event.date },
          end: { date: incrementDate(event.date, 1) },
          description: `Generated by Apres AI (${event.kind}).`
        }
      });
      if (response.status >= 200 && response.status < 300) {
        insertedCount += 1;
      } else {
        errors.push(`HTTP ${response.status}`);
      }
    } catch (error: any) {
      errors.push(String(error?.message ?? error));
    }
  }

  return {
    ok: insertedCount > 0 && errors.length === 0,
    mode: "live",
    calendarId,
    insertedCount,
    errors
  };
}

function incrementDate(isoDate: string, days: number): string {
  const date = new Date(`${isoDate}T00:00:00Z`);
  if (Number.isNaN(date.getTime())) return isoDate;
  date.setUTCDate(date.getUTCDate() + days);
  return date.toISOString().slice(0, 10);
}

